version: '2'

services:
    nginx:
        image: nginx:1.13.6
        container_name: elasticsearch-nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
    php:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: elasticsearch-php
        expose:
            - 9000
        volumes:
            - .:/var/www/html

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
        ports:
            - "9200:9200"
        volumes:
            - .:/var/share/elasticsearch/data
        environment:
            - node.name=my-elastic-node
            - discovery.type=single-node
            - cluster.name=my-docker-cluster
            - network.host=0.0.0.0
            - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    kibana:
        image: docker.elastic.co/kibana/kibana:7.11.2
        links:
            - elasticsearch
        ports:
            - "5601:5601"
        environment:
            - elasticsearch.hosts=http://elasticsearch:9200
            - server.host=0.0.0.0
